### ISSUE TITLE
GeometryGeneratorTest leads an exception 

### ISSUE THREAD

**Issue by mhdfahadCS** [BenzclyZhang/BimSPARQL#1]
I want to test GeometryGeneratorTest, I dont find your input, so tested with my own ifc file. The code is compiled sucessfully but at exception at run time  
java.lang.NullPointerException
	at org.ifcopenshell.IfcGeomServerClient.askForMore(IfcGeomServerClient.java:447)
	at org.ifcopenshell.IfcGeomServerClient.loadModel(IfcGeomServerClient.java:63)
	at org.ifcopenshell.IfcOpenShellModel.<init>(IfcOpenShellModel.java:62)
	at org.ifcopenshell.IfcOpenShellEngine.openModel(IfcOpenShellEngine.java:79)
	at nl.tue.ddss.bimsparql.geometry.GeometryGenerator.generateGeometry(GeometryGenerator.java:103)
	at nl.tue.ddss.bimsparql.geometry.GeometryGenerator.generateGeometry(GeometryGenerator.java:74)
	at nl.tue.ddss.bimsparql.GeometryGeneratorTest.main(GeometryGeneratorTest.java:38)

I have printed output at various points: 
 ifcOpenShellEngine =org.ifcopenshell.IfcOpenShellEngine@eb21112
 iden 65287
 going to write iden: 65287
 s : com.google.common.io.LittleEndianDataOutputStream@5c18298f
 iden 65286
 going to write iden: 65286
 s : com.google.common.io.LittleEndianDataOutputStream@5c18298f
Exception in thread "main" model java.io.FileInputStream@52525845
dos null

It executed two times ifc objects but then exception at dis.readInt() != MORE , see code below 

 private void askForMore() throws IOException {
		hasMore = false;
		if (dis.readInt() != MORE) {
			LOGGER.error("Invalid command sequence encountered");
			throw new IOException();
		}

**Comment by raghavi23** [comment]
Hi,
To generate geometry triples it is mentioned that to load /exe folder of IfcOpenShell-BIMserver-plugin into resource folder.Was trying that to generate geometry.but i couldnt find the exe folder so i paseted all the src code into resource folder and tried. still facing NULLPOINTEREXCEPTION and dependancy issue.how to resolve it to get geometry triples ?

**Comment by rameshgowtham** [comment]
I had the same issues. resolved using the following steps.

1. Download exe folder the contains the executable version same as required in IfcGeomServerClient.java -  "IfcOpenShell-0.5.0-dev" . in my case I found the required version in "IfcOpenShell-BIMserver-plugin-ifcopenshellplugin-0.5.6"

2. make sure the IfcgeomServer is inside "BimSPARQL/src/main/resources/exe/64/osx" and the path of GeometryGenerator.java , .getResource("exe/64/osx/IfcGeomServer"). 

3. if you are Mac user then make sure you have to give the readable, writable and executable permission to files in exe folder. I have used the command "chmod -R 777 BimSPARQL/"
